services:
  broker-service:
    build:
      context: ./broker-service
      dockerfile: ./broker-service.dockerfile
    restart: always
    ports:
      #my pc - docker
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
